name: CI

on:
  pull_request:
    branches:
      -master
    paths-ignore:
      - "*.md"
      - "*.txt"
      - "doxyfile"
  workflow_dispatch:

concurrency:
  group: ci-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  testrunner:
    strategy:
      fail-fast: true
      matrix:
        sanitizer: [none, address]
        type: [RelWithDebInfo, Release]
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build
        run: |
          if [ "${{ matrix.sanitizer }}" = "none" ]; then
            ./build.sh -t "${{ matrix.type }}"
          else
            ./build.sh -t "${{ matrix.type }}" -o "-DCMAKE_CXX_FLAGS=-fsanitize=${{ matrix.sanitizer }}"
          fi
      - name: Run tests
        run: |
          git lfs install
          git lfs pull

          cd test
          tar -xvzf input.tar.gz
          cd ..

          for shrinkingFactor in 64 128 256; do
            for threadCount in 1 2 4; do
              for case in mok_structure mok_fluid; do
                    echo "Running $case on $threadCount threads with $shrinkingFactor shrinking ..."
                    export OMP_NUM_THREADS=$threadCount
                    if ! build/bin/mcgs_testrunner                \
                            test/${case}.mm test/${case}_rhs.mm   \
                            -s $shrinkingFactor                   \
                            -i 1e2
                      then exit 1
                    fi
              done
            done
          done
